### ISSUE TITLE
代码块显示问题

### ISSUE THREAD

**Issue by dasoncheng** [guowenfh/vue-webpack#1]
http://guowenfh.github.io/2016/03/28/vue-webpack-06-router/#more
中有代码块的展示，请问是用的什么工具，默认的Markdown做不出这种效果

**Comment by guowenfh** [comment]
@DasonCheng  就是markdown啊，

"```“这里写语言类型
代码写在这，把双引号删了
”```“

**Comment by dasoncheng** [comment]
![image](https://cloud.githubusercontent.com/assets/16243342/14371104/a9cfbac6-fd66-11e5-9ee9-4a1139724c04.png)

谢啦！不过还需要加对应的样式吗，还是说解释器的不同导致最终效果不同？

**Comment by guowenfh** [comment]
@DasonCheng 不同的解释器样式不一样
