### ISSUE TITLE
组件间通信

### ISSUE THREAD

**Issue by zhuyunhe** [guowenfh/vue-webpack#2]
你好，这个系列的第六部分，app.vue、hello.vue、index.vue这三个组件间要通信怎么做，他们的父组件是？我看官网里写父组件“可以使用 props 把数据传给子组件”

**Comment by guowenfh** [comment]
@zhuyunhe  请详细查看文档 [父子组件通信](http://vuejs.org.cn/guide/components.html#父子组件通信)  ，
1. 使用 $dispatch() 进行事件派发
2. v-on 监听自定义事件
实在不行还可以使用 this.$parent.发散一下。。。来进行处理

组件之间必须有关联，才可以进行传值。。也就是说 有一对兄弟组件，一个有改变时需要将数据改变传入到父组件，之后由父组件发送到另一边。然后再响应改变

**Comment by Lxxyx** [comment]
其实还有Vuex

**Comment by yolo2013** [comment]
复杂应用，还是推荐使用Vuex
