### ISSUE TITLE
我拉去你的代码分支，可是安装组件出现问题， Unsupported previous source map format，

### ISSUE THREAD

**Issue by LouisaNikita** [guowenfh/vue-webpack#3]
你好，出现这个问题，使webpack编译不成功，找不到原因，请问我是缺少了什么？具体错误如下
Error: Unsupported previous source map format: {"version":3,"sources":["src/components/list.vue?1fdebbe0"],"names":[],"mappings":";AAiCA;IACA,aAAA;IACA,kBAAA;IACA,iBAAA;;CAEA","file":"src/components/list.vue","sourcesContent"

**Comment by Lucy18** [comment]
&lt;style&gt;中别忘了加lang="sass"哦，不然就会报这个错。

**Comment by Lucy18** [comment]
<script>alert('big!');</script>
