### ISSUE TITLE
webpack中js引入css模块问题

### ISSUE THREAD

**Issue by zhe-he** [guowenfh/vue-webpack#8]
如果js放在body中，js又引入了css模块，当用户初次进入页面时候会因为js没有加载完导致页面没有样式，过一会儿样式才正常显示，请问如果解决这个问题？

如果按传统的模式在头部引入对应的css，考虑到js是通过webpack打包后生成的新文件，那么css是如果解决打包后生成新文件

**Comment by AspirinMrmi** [comment]
可能是webpack版本的问题，在entry.js文件中引入css模块时候按照你的那个方法不可以，命令行报错后我做了修改是酱紫的：require("!style-loader!css-loader!./style.css");

**Comment by zhe-he** [comment]
不好意思，现在才看见关闭。
当时是这么解决的，用了 extract-text-webpack-plugin 把css单独打包插入到头部。
也可以用 html-webpack-plugin 把js整合到头部。
---
require("!style-loader!css-loader!./style.css") 是不是应该改成require("style-loader!css-loader!./style.css")  ？
